// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBe91XyvGmw49cv0TvleQwA1fMytsgRO98',
    appId: '1:977043310997:web:6d3d6ee05d81b37e4fce9c',
    messagingSenderId: '977043310997',
    projectId: 'hashemtest33',
    authDomain: 'hashemtest33.firebaseapp.com',
    storageBucket: 'hashemtest33.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCy-eA-l4Y0AZGP8mA3lIfalH5ilpg-TVY',
    appId: '1:977043310997:android:daf2174bb88ae6ff4fce9c',
    messagingSenderId: '977043310997',
    projectId: 'hashemtest33',
    storageBucket: 'hashemtest33.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjOYB4A84xgy4RJhbPPzwq7ouWQA-quvw',
    appId: '1:977043310997:ios:15cbfc07a2a1b7364fce9c',
    messagingSenderId: '977043310997',
    projectId: 'hashemtest33',
    storageBucket: 'hashemtest33.appspot.com',
    iosBundleId: 'com.example.socialApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjOYB4A84xgy4RJhbPPzwq7ouWQA-quvw',
    appId: '1:977043310997:ios:15cbfc07a2a1b7364fce9c',
    messagingSenderId: '977043310997',
    projectId: 'hashemtest33',
    storageBucket: 'hashemtest33.appspot.com',
    iosBundleId: 'com.example.socialApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBe91XyvGmw49cv0TvleQwA1fMytsgRO98',
    appId: '1:977043310997:web:7ca45dcd5e16da124fce9c',
    messagingSenderId: '977043310997',
    projectId: 'hashemtest33',
    authDomain: 'hashemtest33.firebaseapp.com',
    storageBucket: 'hashemtest33.appspot.com',
  );
}
